"""
权限种子数据

初始化权限配置和角色权限关联数据
"""
from typing import List, Dict, Any
from app.common.permission_constants import RoleType, PermissionCode, GLOBAL_TENANT_ID


def get_permission_data() -> List[Dict[str, Any]]:
    """获取权限配置种子数据"""
    return [
        {
            "permission_code": PermissionCode.PROJECT_CREATE,
            "permission_name": "创建项目",
            "permission_value": "/api/v1/projects",
            "http_method": "POST",
            "description": "创建新项目（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.PROJECT_DELETE,
            "permission_name": "删除项目",
            "permission_value": "/api/v1/projects/{project_id}",
            "http_method": "DELETE",
            "description": "删除项目（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.PROJECT_UPDATE,
            "permission_name": "更新项目",
            "permission_value": "/api/v1/projects/{project_id}",
            "http_method": "PUT",
            "description": "更新项目信息（平台管理员或项目管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.PROJECT_MEMBER_ADD,
            "permission_name": "添加项目成员",
            "permission_value": "/api/v1/projects/{project_id}/user/batch_save",
            "http_method": "POST",
            "description": "添加项目成员（平台管理员或项目管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.PROJECT_MEMBER_DELETE,
            "permission_name": "删除项目成员",
            "permission_value": "/api/v1/projects/{project_id}/user/batch_remove",
            "http_method": "POST",
            "description": "删除项目成员（平台管理员或项目管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.PROJECT_NAMESPACE_CONFIG,
            "permission_name": "配置项目自定义镜像namespace",
            "permission_value": "/api/v1/projects/project-image-build-namespace/{project_id}",
            "http_method": "PUT",
            "description": "配置项目自定义镜像namespace（平台管理员或项目管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.CLUSTER_CREATE,
            "permission_name": "创建集群",
            "permission_value": "/api/v1/k8s/clusters",
            "http_method": "POST",
            "description": "创建K8s集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.CLUSTER_UPDATE,
            "permission_name": "更新集群",
            "permission_value": "/api/v1/k8s/clusters/{cluster_id}",
            "http_method": "PUT",
            "description": "更新K8s集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.CLUSTER_DELETE,
            "permission_name": "删除集群",
            "permission_value": "/api/v1/k8s/clusters/{cluster_id}",
            "http_method": "DELETE",
            "description": "删除K8s集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.STORAGE_CREATE,
            "permission_name": "创建存储",
            "permission_value": "/api/v1/storage",
            "http_method": "POST",
            "description": "创建存储资源（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.STORAGE_UPDATE,
            "permission_name": "更新存储",
            "permission_value": "/api/v1/storage/{storage_id}",
            "http_method": "PUT",
            "description": "更新存储资源（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.STORAGE_DELETE,
            "permission_name": "删除存储",
            "permission_value": "/api/v1/storage/{storage_id}",
            "http_method": "DELETE",
            "description": "删除存储资源（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.STORAGE_BIND_CLUSTERS,
            "permission_name": "存储绑定集群",
            "permission_value": "/api/v1/storage/{storage_id}/bind-clusters",
            "http_method": "POST",
            "description": "绑定存储到集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.STORAGE_UNBIND_CLUSTERS,
            "permission_name": "存储解绑集群",
            "permission_value": "/api/v1/storage/{storage_id}/unbind-clusters",
            "http_method": "DELETE",
            "description": "解绑存储与集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.IMAGE_CREATE,
            "permission_name": "创建镜像",
            "permission_value": "/api/v1/repository_images/create",
            "http_method": "POST",
            "description": "创建镜像（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.IMAGE_UPDATE,
            "permission_name": "更新镜像",
            "permission_value": "/api/v1/repository_images/{image_id}",
            "http_method": "PUT",
            "description": "更新镜像（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.IMAGE_DELETE,
            "permission_name": "删除镜像",
            "permission_value": "/api/v1/repository_images/{image_id}",
            "http_method": "DELETE",
            "description": "删除镜像（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.REPOSITORY_CREATE,
            "permission_name": "创建模型仓库",
            "permission_value": "/api/v1/repository",
            "http_method": "POST",
            "description": "创建模型仓库（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.REPOSITORY_UPDATE,
            "permission_name": "更新模型仓库",
            "permission_value": "/api/v1/repository/{repository_id}",
            "http_method": "PUT",
            "description": "更新模型仓库（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.REPOSITORY_DELETE,
            "permission_name": "删除模型仓库",
            "permission_value": "/api/v1/repository/{repository_id}",
            "http_method": "DELETE",
            "description": "删除模型仓库（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "permission_code": PermissionCode.REPOSITORY_BIND_CLUSTERS,
            "permission_name": "仓库绑定集群",
            "permission_value": "/api/v1/repository/{repository_id}/bind-clusters",
            "http_method": "POST",
            "description": "绑定仓库到集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.REPOSITORY_UNBIND_CLUSTERS,
            "permission_name": "仓库解绑集群",
            "permission_value": "/api/v1/repository/{repository_id}/unbind-clusters",
            "http_method": "DELETE",
            "description": "解绑仓库与集群（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.CLUSTER_BIND_STORAGE,
            "permission_name": "集群绑定存储",
            "permission_value": "/api/v1/k8s/{cluster_id}/{storage_id}/bind-storage",
            "http_method": "POST",
            "description": "集群绑定存储（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.CLUSTER_BIND_REPOSITORY,
            "permission_name": "集群绑定仓库",
            "permission_value": "/api/v1/k8s/{cluster_id}/{repository_id}/bind-repository",
            "http_method": "POST",
            "description": "集群绑定仓库（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.BASE_MODEL_CREATE,
            "permission_name": "创建基座模型",
            "permission_value": "/api/v1/models/base",
            "http_method": "POST",
            "description": "创建基座模型（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.BASE_MODEL_UPDATE,
            "permission_name": "更新基座模型",
            "permission_value": "/api/v1/models/base",
            "http_method": "PUT",
            "description": "更新基座模型（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_CREATE,
            "permission_name": "新增标签",
            "permission_value": "/api/v1/tags/classes",
            "http_method": "POST",
            "description": "新增标签分类（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_UPDATE,
            "permission_name": "编辑标签",
            "permission_value": "/api/v1/tags/classes/{tag_class_id}",
            "http_method": "PUT",
            "description": "编辑标签分类（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_DELETE,
            "permission_name": "删除标签",
            "permission_value": "/api/v1/tags/classes/{tag_class_id}",
            "http_method": "DELETE",
            "description": "删除标签分类（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_ELEMENTS_CREATE,
            "permission_name": "新增标签元素",
            "permission_value": "/api/v1/tags/elements",
            "http_method": "POST",
            "description": "新增标签元素（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_ELEMENTS_UPDATE,
            "permission_name": "编辑标签元素",
            "permission_value": "/api/v1/tags/elements/{tag_element_id}",
            "http_method": "PUT",
            "description": "编辑标签元素（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.TAG_ELEMENTS_DELETE,
            "permission_name": "删除标签元素",
            "permission_value": "/api/v1/tags/elements/{tag_element_id}",
            "http_method": "DELETE",
            "description": "删除标签元素（仅平台管理员）",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.BUSINESS_ATTR_CREATE,
            "permission_name": "创建业务属性",
            "permission_value": "/api/v1/business-attr/create",
            "http_method": "POST",
            "description": "创建业务属性",
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "permission_code": PermissionCode.BUSINESS_ATTR_DELETE,
            "permission_name": "删除业务属性",
            "permission_value": "/api/v1/business-attr/delete",
            "http_method": "DELETE",
            "description": "删除业务属性",
            "tenant_id": GLOBAL_TENANT_ID,
        },
    ]


def get_role_permission_data() -> List[Dict[str, Any]]:
    """获取角色权限关联种子数据"""
    return [
        # 平台管理员权限
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_MEMBER_ADD,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_MEMBER_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.PROJECT_NAMESPACE_CONFIG,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.CLUSTER_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.CLUSTER_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.CLUSTER_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.STORAGE_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.STORAGE_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.STORAGE_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.STORAGE_BIND_CLUSTERS,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.STORAGE_UNBIND_CLUSTERS,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.IMAGE_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.IMAGE_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.IMAGE_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.REPOSITORY_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.REPOSITORY_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.REPOSITORY_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.REPOSITORY_BIND_CLUSTERS,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.REPOSITORY_UNBIND_CLUSTERS,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.CLUSTER_BIND_STORAGE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.CLUSTER_BIND_REPOSITORY,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.BASE_MODEL_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.BASE_MODEL_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_ELEMENTS_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_ELEMENTS_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.TAG_ELEMENTS_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.BUSINESS_ATTR_CREATE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        {
            "role_type": RoleType.PLATFORM_ADMIN,
            "permission_code": PermissionCode.BUSINESS_ATTR_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,
        },
        # 项目管理员权限
        {
            "role_type": RoleType.PROJECT_ADMIN,
            "permission_code": PermissionCode.PROJECT_UPDATE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PROJECT_ADMIN,
            "permission_code": PermissionCode.PROJECT_MEMBER_ADD,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PROJECT_ADMIN,
            "permission_code": PermissionCode.PROJECT_MEMBER_DELETE,
            "tenant_id": GLOBAL_TENANT_ID,  
        },
        {
            "role_type": RoleType.PROJECT_ADMIN,
            "permission_code": PermissionCode.PROJECT_NAMESPACE_CONFIG,
            "tenant_id": GLOBAL_TENANT_ID,
        },
    ]
