from app.utils.showcase_sample_files import make_showcase_sample_path

TENANT_ID = "lab"
SHOWCASE_USER = {
    "username": "showcase_admin",
    "email": "showcase_admin@example.local",
    "hashed_password": "showcase-local-only",
}

PROJECTS = [
    {
        "name": "演示项目 - 大模型训练",
        "description": "覆盖训练、推理、评估、标注、清洗、增强和洞察主流程的演示项目。",
        "image_build_namespace": "showcase-llm",
    },
    {
        "name": "演示项目 - 机器学习",
        "description": "覆盖机器学习数据集、Notebook 和在线标注流程的演示项目。",
        "image_build_namespace": "showcase-ml",
    },
]

KUBERNETES = {
    "name": "preview-gpu-cluster",
    "config": "kind: Config\napiVersion: v1\nclusters: []\ncontexts: []\nusers: []\n",
    "api_server": "https://k8s-preview.example.local",
    "description": "演示集群，仅用于本地展示资源选择与任务状态。",
    "status": "online",
    "version": "v1.28.8",
    "node_number": 6,
    "ext": {
        "graphics_card_resource_type": [
            {
                "category": "NVIDIA",
                "resource_types": [
                    {"type": "GPU", "model": "A800", "memory": "80GB"},
                    {"type": "GPU", "model": "L20", "memory": "48GB"},
                ],
            }
        ]
    },
}

STORAGE = {
    "name": "preview-minio",
    "type": "minio",
    "description": "演示对象存储，用于模型、数据集和评估产物预览。",
    "status": "连接正常",
    "config": {
        "endpoint": "http://minio-preview.example.local:9000",
        "bucket": "deepexilab-preview",
    },
    "cluster_number": 1,
    "is_init": True,
}

REPOSITORY = {
    "name": "preview-harbor",
    "repository_address": "harbor-preview.example.local/deepexilab",
    "auth_type": "username_password",
    "auth_config": {"username": "preview"},
    "manager_address": "https://harbor-preview.example.local",
    "cluster_number": 1,
    "status": "连接正常",
    "namespace": "deepexilab",
    "type": "private_harbor",
    "config": {},
}

TRAINING_DATASETS = [
    {
        "name": "showcase-SFT-PromptResponse-客服问答",
        "description": "文本生成 SFT Prompt+Response 演示数据，可用于标注、清洗、洞察和训练。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "sft",
        "dataset_format": "prompt-response",
        "usage": "training",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["system", "prompt", "response"],
        "total_samples": 60,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-SFT-RoleBased-多轮客服",
        "description": "文本生成 SFT Role-Based 多轮对话演示数据。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "sft",
        "dataset_format": "role-based",
        "usage": "training",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["messages"],
        "total_samples": 60,
        "publish": 0,
        "processing_status": "completed",
    },
    {
        "name": "showcase-DPO-Alpaca-偏好问答",
        "description": "DPO Alpaca 偏好数据演示。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "dpo",
        "dataset_format": "alpaca",
        "usage": "training",
        "path": make_showcase_sample_path("dpo/qa/text_generation_qa_dpo_alpaca.jsonl"),
        "metadata_fields": ["instruction", "input", "chosen", "rejected"],
        "total_samples": 40,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-GRPO-数学推理奖励",
        "description": "RFT-GRPO 数学推理奖励数据演示。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "grpo",
        "dataset_format": "grpo",
        "usage": "training",
        "path": make_showcase_sample_path("grpo/qa/text_generation_qa_grpo.jsonl"),
        "metadata_fields": ["prompt", "reward_model", "extra_info"],
        "total_samples": 60,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-图像理解SFT-质检问答",
        "description": "图像理解 SFT Role-Based 演示数据。",
        "version": "V1",
        "dataset_type": "image-understanding",
        "training_method_type": "sft",
        "dataset_format": "role-based",
        "usage": "training",
        "path": make_showcase_sample_path("showcase/image_understanding_role_based.jsonl"),
        "metadata_fields": ["messages", "images"],
        "total_samples": 3,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-图像生成SFT-商品海报",
        "description": "图像生成 SFT image-prompt 演示数据。",
        "version": "V1",
        "dataset_type": "image-generation",
        "training_method_type": "sft",
        "dataset_format": "image-prompt",
        "usage": "training",
        "path": make_showcase_sample_path("showcase/image_generation_prompt.jsonl"),
        "metadata_fields": ["prompt", "image"],
        "total_samples": 3,
        "publish": 0,
        "processing_status": "completed",
    },
    {
        "name": "showcase-验证集-客服问答",
        "description": "验证数据集，覆盖已发布状态。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "sft",
        "dataset_format": "prompt-response",
        "usage": "validation",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["system", "prompt", "response"],
        "total_samples": 20,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-测试数据创建中",
        "description": "测试数据处理中状态演示，发布状态显示为 -。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "sft",
        "dataset_format": "prompt-response",
        "usage": "test",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["system", "prompt", "response"],
        "total_samples": 20,
        "publish": 2,
        "processing_status": "pending",
    },
    {
        "name": "showcase-测试数据创建失败",
        "description": "测试数据失败状态演示，发布状态显示为 -。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "sft",
        "dataset_format": "prompt-response",
        "usage": "test",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["system", "prompt", "response"],
        "total_samples": 20,
        "publish": 3,
        "processing_status": "failed",
        "processing_error": "演示数据：文件字段缺失，等待重新上传。",
    },
    {
        "name": "showcase-业务训练-工单质检",
        "description": "业务训练数据集，覆盖 business 格式和业务属性展示。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "business",
        "dataset_format": "business",
        "usage": "business_training",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["ticket_id", "question", "answer", "risk_level"],
        "total_samples": 30,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-业务测试-售后回访",
        "description": "业务测试数据集，覆盖未发布 business 数据。",
        "version": "V1",
        "dataset_type": "text-generation",
        "training_method_type": "business",
        "dataset_format": "business",
        "usage": "business_test",
        "path": make_showcase_sample_path("sft/qa/text_generation_qa_prompt_response.jsonl"),
        "metadata_fields": ["ticket_id", "question", "answer", "channel"],
        "total_samples": 30,
        "publish": 0,
        "processing_status": "completed",
    },
]

MACHINE_LEARNING_DATASETS = [
    {
        "name": "showcase-文本分类-单标签",
        "description": "机器学习文本分类单标签演示数据。",
        "version": "V1",
        "task_type": "text_classification",
        "data_type": "text",
        "annotation_type": "text_classification",
        "template_type": "text_classification_single_label",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("machine_learning/text_cls_short_single.jsonl"),
        "metadata_fields": ["text", "label"],
        "sample_count": 20,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-实体识别-客服工单",
        "description": "机器学习实体识别演示数据。",
        "version": "V1",
        "task_type": "text_entity_recognition",
        "data_type": "text",
        "annotation_type": "entity_recognition",
        "template_type": "entity_recognition",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("machine_learning/ner_text.jsonl"),
        "metadata_fields": ["text", "entities"],
        "sample_count": 20,
        "publish": 0,
        "processing_status": "completed",
    },
    {
        "name": "showcase-图像分类-质检",
        "description": "机器学习图像分类演示数据。",
        "version": "V1",
        "task_type": "image_classification",
        "data_type": "image",
        "annotation_type": "image_classification",
        "template_type": "image_classification_single_label",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("showcase/ml_image_classification.jsonl"),
        "metadata_fields": ["image", "label"],
        "sample_count": 3,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-物体检测-包裹",
        "description": "机器学习物体检测演示数据。",
        "version": "V1",
        "task_type": "object_detection",
        "data_type": "image",
        "annotation_type": "object_detection",
        "template_type": "object_detection_bbox",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("showcase/ml_object_detection.jsonl"),
        "metadata_fields": ["image", "annotations"],
        "sample_count": 3,
        "publish": 1,
        "processing_status": "completed",
    },
    {
        "name": "showcase-图像分割-多模板",
        "description": "机器学习图像分割演示数据，覆盖实例分割和语义分割验收。",
        "version": "V1",
        "task_type": "image_segmentation",
        "data_type": "image",
        "annotation_type": "image_segmentation",
        "template_type": "instance_segmentation_mask",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("showcase/ml_segmentation.jsonl"),
        "metadata_fields": ["image", "annotations"],
        "sample_count": 3,
        "publish": 0,
        "processing_status": "completed",
    },
    {
        "name": "showcase-文本分类-处理中",
        "description": "机器学习数据集处理中状态演示。",
        "version": "V1",
        "task_type": "text_classification",
        "data_type": "text",
        "annotation_type": "text_classification",
        "template_type": "text_classification_single_label",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("machine_learning/text_cls_short_single.jsonl"),
        "metadata_fields": ["text", "label"],
        "sample_count": 20,
        "publish": 2,
        "processing_status": "pending",
    },
    {
        "name": "showcase-物体检测-解析失败",
        "description": "机器学习数据集失败状态演示。",
        "version": "V1",
        "task_type": "object_detection",
        "data_type": "image",
        "annotation_type": "object_detection",
        "template_type": "object_detection_bbox",
        "source_type": "jsonl",
        "path": make_showcase_sample_path("showcase/ml_object_detection.jsonl"),
        "metadata_fields": ["image", "annotations"],
        "sample_count": 3,
        "publish": 3,
        "processing_status": "failed",
    },
]
