packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'
overrides:
  '@antv/g-base': 0.5.16
  '@antv/g-math': 0.1.9
  '@types/react': 18.3.31
  '@types/react-dom': 18.3.7
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
