"""
镜像种子数据
"""

from typing import List, Dict, Any

from app.schemas.inference_task import BackendEnum
from app.schemas.repository_image import ImageType, CardType, CardModel, CudaVersion


def get_image_data() -> List[Dict[str, Any]]:
    """获取镜像种子数据"""
    return [
        # 大模型 - 在线notebook
        {
            "image": "jupyter/deepexi-notebook:datascience-cpu-python312-ubuntu24.04-ai",
            "type": ImageType.LLM_NOTEBOOK,
            "sub_type": None,
            "describe": "CPU镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:torch_2.5-cann_8.0.rc1-py311-ubuntu22.04-ai",
            "type": ImageType.LLM_NOTEBOOK,
            "sub_type": None,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.5-cuda_12.1-py312-ubuntu24.04-ai",
            "type": ImageType.LLM_NOTEBOOK,
            "sub_type": None,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        # 机器学习 - 在线notebook
        {
            "image": "jupyter/deepexi-notebook:datascience-cpu-python312-ubuntu24.04-ai",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": None,
            "describe": "CPU镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:torch_2.5-cann_8.0.rc1-py311-ubuntu22.04-ai",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": None,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.5-cuda_12.1-py312-ubuntu24.04-ai",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": None,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.5-cuda_12.1-py312-ubuntu24.04-ml",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": BackendEnum.ML.value,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.11-cuda_12.8-py312-ubuntu24.04-ml",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": BackendEnum.ML.value,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:torch_2.5-cann_8.0.rc1-py311-ubuntu22.04-ml",
            "type": ImageType.ML_NOTEBOOK,
            "sub_type": BackendEnum.ML.value,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": f"llamafactory:0.9.4-{CardType.GPU.value}-{ImageType.TEXT_GENERATION_SFT.desc}",
            "type": ImageType.TEXT_GENERATION_SFT,
            "sub_type": None,
            "describe": f"{ImageType.TEXT_GENERATION_SFT.desc}（默认GPU镜像）",
            "card_category": CardType.GPU.value,
            "card_model": None,  # 默认GPU镜像，不绑定特定型号
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": f"llamafactory:0.9.4-{CardType.NPU.value}-{ImageType.TEXT_GENERATION_SFT.desc}",
            "type": ImageType.TEXT_GENERATION_SFT,
            "sub_type": None,
            "describe": f"{ImageType.TEXT_GENERATION_SFT.desc}（默认NPU镜像）",
            "card_category": CardType.NPU.value,
            "card_model": None,  # 默认NPU镜像，不绑定特定型号
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "vllm-openai:v0.11.2",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.VLLM.value,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.5-cuda_12.1-py312-ubuntu24.04-ml",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.ML.value,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:pytorch_2.11-cuda_12.8-py312-ubuntu24.04-ml",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.ML.value,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "jupyter/deepexi-notebook:torch_2.5-cann_8.0.rc1-py311-ubuntu22.04-ml",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.ML.value,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "deepexi-data-juicer:v0.1",
            "type": ImageType.DATA_CLEANING,
            "describe": "CPU镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "inference-client:1.0.0",
            "type": ImageType.INFERENCE_IMAGE,
            "describe": "cpu镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "vllm-service:v0.11.2",
            "type": ImageType.INFERENCE_IMAGE,
            "describe": "GPU镜像",
            "card_category": CardType.GPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "vllm-ascend:v0.13.0",
            "type": ImageType.INFERENCE_IMAGE,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "deepexi-lab-model-download:v1.1.0",
            "type": ImageType.MODEL_DOWNLOAD,
            "describe": "模型下载镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "bitnami/kubectl:1.29",
            "type": ImageType.KUBECTL_IMAGE,
            "describe": "kubectl命令",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "moby/buildkit:v0.12.5",
            "type": ImageType.BUILDKIT_IMAGE,
            "describe": "buildkit镜像构建",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "dgi:v2.5",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.DGI_SERVER.value,
            "describe": "dgi-serve镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "deepexi-opencompass:v0.5.1",
            "type": ImageType.BENCHMARK_IMAGE,
            "sub_type": None,
            "describe": "OpenCompass基准评估镜像",
            "card_category": CardType.CPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
        {
            "image": "vllm-ascend:v0.13.0",
            "type": ImageType.INFERENCE,
            "sub_type": BackendEnum.VLLM.value,
            "describe": "NPU镜像",
            "card_category": CardType.NPU.value,
            "card_model": None,
            "cuda_version": None,
            "python_version": None,
        },
    ]
